

<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>

    <h2>
        <?php print $this->key ;?>
    </h2>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>


<table class="table table-striped" cellspacing="1">
<thead style="background: #286090 ; color: white ; text-align: center">
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Full Adress I</th>
                        <th>Full Adress II</th>
                        <th>Full Adress III</th>
                        <th>Operation</th>
                        <th>Delete</th>
                        <th>Edit</th>
                    </tr>
                    </thead>
                <?php foreach($users as $user): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $user->getIdUtilisateur(); ?></td>
                        <td><?php echo $user->getName(); ?></td>
                        <td><?php echo $user->getAdress(); ?></td>
                        <td><?php echo $user->getAdress(); ?></td>
                        <td><?php echo $user->getAdress(); ?></td>
                        <td>
                             <a href="<?php echo $this->url('add', array('action'=>'add'));?>" class="btn btn-success" role="button">Add New User</a>
                        </td>
                         <td>
                             <a href="<?php echo $this->url('edit', array('action'=>'edit', 'id' => $user->getIdUtilisateur()));?>" class="btn btn-warning" role="button">Edit</a>
                             </td>
                        <td>
                            <a href="<?php echo $this->url('users', array('action'=>'delete', 'id' => $user->getIdUtilisateur()));?>" class="btn btn-danger" role="button">Delete</a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
</table>


<h1>Source </h1>
<code>

    load data from console , command <br>
    php public\index.php user user 10 ( 10 lines for example )


</code>

<!--<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php /*echo $this->translate('Follow Development') */?></h3>
            </div>
            <div class="panel-body">
                <p><?php /*echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') */?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php /*echo $this->translate('ZF2 Development Portal') */?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php /*echo $this->translate('Discover Modules') */?></h3>
            </div>
            <div class="panel-body">
                <p><?php /*echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') */?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php /*echo $this->translate('Explore ZF2 Modules') */?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php /*echo $this->translate('Help &amp; Support') */?></h3>
            </div>
            <div class="panel-body">
                <p><?php /*echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') */?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php /*echo $this->translate('Ping us on IRC') */?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>-->
